name: test-unit
on:
  pull_request:
env:
  GO111MODULE: "on"
jobs:
  test:
    strategy:
      matrix:
        go-version: [ stable ]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Init gocacheprog
        run: |
          wget -q -O /tmp/gocacheprog.tar.gz https://github.com/vearutop/gocacheprog/releases/latest/download/linux_amd64.tar.gz
          tar xf /tmp/gocacheprog.tar.gz -C /tmp
          rm /tmp/gocacheprog.tar.gz
          /tmp/gocacheprog -github-actions-init "https://gocache.example.com?auth=<key>&cache_dir=./build-cache&preload_size=3000000&build_type=unit&mode=shim"

      - name: Test
        shell: bash
        run: |
          time go test -parallel 50 ./...

      - name: Finalize gocacheprog
        if: ${{ always() }}
        run: |
          /tmp/gocacheprog -github-actions-done
